
    #   720p
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
PLAYER_TURN_RATE = 300
PLAYER_MOVE_RATE = 200
LINE_WIDTH = 2
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_CD_SEC = 0.3
POINTS_PER_ASTEROID_HIT = 100
POINTS_PER_SEC = 10